name: Skylife
version: '1.0-SNAPSHOT'
main: com.carinaschoppe.skylife.Skylife
api-version: '1.21'
description: Skylife is a Skywars Main-System Plugin used for a remake of Smash and Skywars
author: [ Carina Sophie Schoppe (LazarusDE), Ceye4n ]
commands:
  start:
    description: Quickstarts a game
    aliases: [ s ]
  join:
    description: Joins a game specify if youve got premium
    aliases: [ ]
  leave:
    description: Leave the current game and go back to the lobby
    aliases: [ l, hub, spawn, lobby, back ]
  playeramount:
    description: Capable of setting the required amount of players for a game
    aliases: [ pm ]
  setlocation:
    description: Capable of setting up the locations for a game
    aliases: [ sl ]
  sethub:
    description: Sets the hub spawn location to your current location
    aliases: [ sh, setspawn ]
  game:
    description: Capable of creating a game
    aliases: [ ]
  stats:
    description: Shows the stats of a player or of yourself
    aliases: [ stat ]
  overview:
    description: Shows an inventory with a list of games to play
    aliases: [ ov, games ]
  skills:
    description: Shows an inventory with a list of the possible skills in form of clickable items
    aliases: [ s, skill ]
  guild:
    description: Manage your guild (create, invite, kick, promote, leave, toggleff, info)
    aliases: [ g, clan, team ]
  msg:
    description: Send a direct message to another player
    aliases: [ message, whisper, w, tell, pm ]
  party:
    description: Manage your party (create, invite, accept, leave, kick, promote, list, invites)
    aliases: [ p ]
  gamesetup:
    description: Opens a GUI to setup a new game pattern with all settings
    aliases: [ gs, setupgame ]
  removespawn:
    description: Removes a spawn location during game setup
    aliases: [ rs, deletespawn ]
  savemessages:
    description: Exports current messages to messages.json for reference
    aliases: [ sm, exportmessages ]
  leaderboard:
    description: Shows the top 10 players for various statistics (points, kills, wins, games, kd)
    aliases: [ lb, top, ranks ]
  givecoins:
    description: Give coins to a player (Admin only)
    aliases: [ addcoins, givecoins ]
  removecoins:
    description: Remove coins from a player (Admin only)
    aliases: [ takecoins, removecoins ]
  deletegame:
    description: Delete a game pattern and all its instances (Admin only)
    aliases: [ dg, removegame, delgame ]
  managegames:
    description: Open the game management GUI (Admin only)
    aliases: [ mg, editgames, gamemanager ]
permissions:
  skylife.*:
    description: Gives access to all Skylife commands
    default: true
    children:
      skylife.user.*: true
      skylife.admin.*: true
  skylife.user.*:
    description: Gives access to all user commands
    default: true
    children:
      skylife.join: true
      skylife.join.random: true
      skylife.join.map: true
      skylife.leave: true
      skylife.start: true
      skylife.stats: true
      skylife.stats.other: true
      skylife.overview: true
      skylife.skills: true
      skylife.guild: true
      skylife.msg: true
      skylife.party: true
      skylife.leaderboard: true
  skylife.admin.*:
    description: Gives access to all admin commands (for admins and devs)
    default: op
    children:
      skylife.admin.create: true
      skylife.admin.save: true
      skylife.admin.delete: true
      skylife.admin.setlocation: true
      skylife.admin.playeramount: true
      skylife.admin.sethub: true
      skylife.admin.gamesetup: true
      skylife.admin.removespawn: true
      skylife.admin.savemessages: true
      skylife.admin.givecoins: true
      skylife.admin.removecoins: true
      skylife.admin.deletegame: true
      skylife.admin.managegames: true
  skylife.join:
    description: Allows joining games
    default: true
  skylife.join.random:
    description: Allows joining random games
    default: true
  skylife.join.map:
    description: Allows joining specific maps
    default: true
  skylife.leave:
    description: Allows leaving games
    default: true
  skylife.start:
    description: Allows quick-starting games
    default: true
  skylife.stats:
    description: Allows viewing own stats
    default: true
  skylife.stats.other:
    description: Allows viewing other players' stats
    default: true
  skylife.overview:
    description: Allows opening game overview
    default: true
  skylife.skills:
    description: Allows viewing skills
    default: true
  skylife.guild:
    description: Allows using guild commands
    default: true
  skylife.msg:
    description: Allows sending messages
    default: true
  skylife.party:
    description: Allows using party commands
    default: true
  skylife.leaderboard:
    description: Allows viewing leaderboards
    default: true
  skylife.admin.givecoins:
    description: Allows giving coins to players
    default: op
  skylife.admin.removecoins:
    description: Allows removing coins from players
    default: op
  skylife.admin.deletegame:
    description: Allows deleting game patterns and instances
    default: op
  skylife.admin.managegames:
    description: Allows managing game patterns via GUI
    default: op
  skylife.admin.create:
    description: Allows creating game patterns (DEV/ADMIN only)
    default: op
  skylife.admin.save:
    description: Allows saving game patterns (DEV/ADMIN only)
    default: op
  skylife.admin.delete:
    description: Allows deleting game patterns via /game command (DEV/ADMIN only)
    default: op
  skylife.admin.setlocation:
    description: Allows setting game locations (DEV/ADMIN only)
    default: op
  skylife.admin.playeramount:
    description: Allows setting player amounts (DEV/ADMIN only)
    default: op
  skylife.admin.sethub:
    description: Allows setting hub spawn (DEV/ADMIN only)
    default: op
  skylife.admin.gamesetup:
    description: Allows opening game setup GUI (DEV/ADMIN only)
    default: op
  skylife.admin.removespawn:
    description: Allows removing spawn locations (DEV/ADMIN only)
    default: op
  skylife.admin.savemessages:
    description: Allows exporting messages (DEV/ADMIN only)
    default: op
  skylife.rank.user:
    description: User rank (default)
    default: true
  skylife.rank.vip:
    description: VIP rank (2x coins, 3 kit slots)
    default: false
  skylife.rank.vipplus:
    description: VIP+ rank (4x coins, 4 kit slots)
    default: false
  skylife.rank.mod:
    description: Moderator rank (4x coins, staff permissions)
    default: false
  skylife.rank.dev:
    description: Developer rank (4x coins, staff permissions)
    default: false
  skylife.rank.admin:
    description: Admin rank (4x coins, highest staff permissions)
    default: op